image: kkarczmarczyk/node-yarn:latest

cache:
  paths:
  - node_modules/

before_script:
  - yarn install --cache-folder yarn-cache

lint:
  script:
   - node ./node_modules/eslint/bin/eslint.js .

jest:
  script:
    - npm run codecov
