image: kkarczmarczyk/node-yarn:latest

cache:
  paths:
  - node_modules/
  - api/node_modules/

before_script:
  - yarn install
  - cd api
  - yarn install
  - cd ..

lint:
  script:
   - node ./node_modules/eslint/bin/eslint.js .

jest:
  script:
    - npm test
