image: kkarczmarczyk/node-yarn:6.9

stages:
  - test
  - build
  - deploy


cache:
  paths:
  - node_modules/
  - ~/.yarn-cache/

before_script:
  - yarn install

lint:
  script:
   - npm run lint

jest:
  script:
    - npm run codecov

e2e:
  script:
    - npm run build
    - 'npm run test:e2e'

web/deploy/staging:
  stage: deploy
  script:
    - npm run build
    - 'npm run deploy:web:staging'
  only:
    - master
  environment:
    name: web/staging
    url: https://staging.app.complt.xyz

web/deploy/production:
  stage: deploy
  script:
    - npm run build
    - 'npm run deploy:web:prod'
  only:
    - master
  environment:
    name: web/production
    url: https://app.complt.xyz
  when: manual

web/deploy/landing:
  stage: deploy
  script:
    - 'npm run deploy:web:landing'
  only:
    - master
  environment:
    name: web/landing
    url: https://complt.xyz
  when: manual

electron/build:
  stage: deploy
  script:
    - 'npm run build:electron'
  artifacts:
    paths:
      - dist/

exponent/deploy:
  stage: deploy
  script:
    - 'npm run deploy:exponent'
  only:
    - master
  environment:
    name: exponent
    url: https://exp.host/@mitchellhamilton/Complt
  when: manual
