image: kkarczmarczyk/node-yarn:latest

stages:
  - test
  - build
  - deploy


cache:
  paths:
  - node_modules/
  - ~/.yarn-cache/

before_script:
  - yarn install

lint:
  script:
   - npm run lint

jest:
  script:
    - npm run codecov

web/source-map:
  stage: deploy
  script:
    - 'npm run build:sentry'
  only:
    - master

web/deploy/staging:
  stage: deploy
  script:
    - npm run build
    - 'npm run deploy:web:staging'
  only:
    - master
  environment:
    name: web/staging
    url: https://staging.app.complt.xyz

web/deploy/production:
  stage: deploy
  script:
    - npm run build
    - 'npm run deploy:web:prod'
  only:
    - master
  environment:
    name: web/production
    url: https://app.complt.xyz
  when: manual

  electron/build:
    stage: deploy
    script:
      - 'npm run build:electron'
    artifacts:
      paths:
        - dist/
