image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - cd api
  - npm install
  - cd ..

lint:
  script:
   - node ./node_modules/eslint/bin/eslint.js .

jest:
  script:
    - npm test
